### ISSUE TITLE
https://poweredby-sdk-release.dosh.com is down, package cannot be resolved

### ISSUE THREAD

**Issue by afonsocdc** [dosh-com/powered-by-dosh-ios-releases#1]
Hello,

We are using `2.7.1` and we cannot resolve the swift packages because at the time of writing this the domain is down.

e.g `https://poweredby-sdk-release.dosh.com/ios/2.7.1/DoshCardVaulting.zip`

**Comment by afonsocdc** [comment]
@dosh-ios-dev @johntmcintosh

**Comment by johntmcintosh** [comment]
@afonsocdc thanks for the report. We are actively investigating what caused the domain resolution to fail and will report back here with an update.

**Comment by einstein-nguyen** [comment]
@afonsocdc The issue has been resolved and the domain is back up!

**Comment by raghulk** [comment]
Looks like the same issue is back?
